// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB1W0z1DaU4SoYkc2ZmSR-3n00u7LQ9umE',
    appId: '1:95673725254:web:938d3488e5b3a5ae983547',
    messagingSenderId: '95673725254',
    projectId: 'flutter-firebase-bloc-ng-notes',
    authDomain: 'flutter-firebase-bloc-ng-notes.firebaseapp.com',
    storageBucket: 'flutter-firebase-bloc-ng-notes.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC58fmttsXZ6M7utIqxnTBVynq3bDlbFQI',
    appId: '1:95673725254:android:188c215b0de01023983547',
    messagingSenderId: '95673725254',
    projectId: 'flutter-firebase-bloc-ng-notes',
    storageBucket: 'flutter-firebase-bloc-ng-notes.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCm-jpd0YGvqvQ6zAqFPmYw0fcdxBXQRM8',
    appId: '1:95673725254:ios:90f62c32b15ee118983547',
    messagingSenderId: '95673725254',
    projectId: 'flutter-firebase-bloc-ng-notes',
    storageBucket: 'flutter-firebase-bloc-ng-notes.appspot.com',
    iosClientId: '95673725254-17jvfbehkljlojl4oq1amp538dr084ln.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterFirebaseBlocNotes',
  );
}
